// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: testService.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Grpcstreamserver {
  public static partial class TestService
  {
    static readonly string __ServiceName = "grpcstreamserver.TestService";

    static readonly grpc::Marshaller<global::Grpcstreamserver.MessageRequest> __Marshaller_MessageRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpcstreamserver.MessageRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Grpcstreamserver.TestMessage> __Marshaller_TestMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpcstreamserver.TestMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::Grpcstreamserver.MessageRequest, global::Grpcstreamserver.TestMessage> __Method_GetMessages = new grpc::Method<global::Grpcstreamserver.MessageRequest, global::Grpcstreamserver.TestMessage>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetMessages",
        __Marshaller_MessageRequest,
        __Marshaller_TestMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Grpcstreamserver.TestServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TestService</summary>
    public abstract partial class TestServiceBase
    {
      public virtual global::System.Threading.Tasks.Task GetMessages(global::Grpcstreamserver.MessageRequest request, grpc::IServerStreamWriter<global::Grpcstreamserver.TestMessage> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TestService</summary>
    public partial class TestServiceClient : grpc::ClientBase<TestServiceClient>
    {
      /// <summary>Creates a new client for TestService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TestServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TestService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TestServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TestServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TestServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Grpcstreamserver.TestMessage> GetMessages(global::Grpcstreamserver.MessageRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetMessages(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Grpcstreamserver.TestMessage> GetMessages(global::Grpcstreamserver.MessageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetMessages, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TestServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TestServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TestServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetMessages, serviceImpl.GetMessages).Build();
    }

  }
}
#endregion
